### ISSUE TITLE
OSX Key Error - Data

### ISSUE THREAD

**Issue by macjonesnz** [highmindedlowlife/trading-scripts#6]
./base_scanner.py 

Settings:
 Namespace(days=60, delete_old_alerts=True, drop=0.95, exchange='BTRX', low_or_close=3, market='BTC', minimum_volume=1, minutes=60, sensitivity=3, six_candle_up=1.08, skip=12, split_the_difference=False)
Traceback (most recent call last):
  File "./base_scanner.py", line 303, in <module>
    main()
  File "./base_scanner.py", line 253, in main
    scanner.scan_for_bases_and_set_alerts()
  File "./base_scanner.py", line 191, in scan_for_bases_and_set_alerts
    coins = self.get_coins(self._settings.exchange)
  File "./base_scanner.py", line 40, in get_coins
    for x in coin_list['data']:
KeyError: 'data'

**Comment by macjonesnz** [comment]
looks like API key issue... closing.....
